name: CI for Next.js

on:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Echo Linting (Testlauf)
        run: echo "Running Linting checks..."

      - name: Run Linting
        run: npm run lint

  # Testing Job
  test:
    runs-on: ubuntu-latest
    needs: lint  
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Echo Testing (Testlauf)
        run: echo "Running Tests..."

      - name: Run Tests
        run: npm test

  # Deployment Simulation Job
  deploy:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Deployment Step
        run: echo "Deployment successful"
